---
title: "Results"
author: "r Sys.getenv('USERNAME')"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r import}
library(dplyr)
library(glue)
library(data.table)
library(ggplot2)

# Function to convert codes, titles, and probs to NA if title is "Insufficient Information"
insufficient_na <- function(df, code, title, prob) {
  tf = !is.na(df[title])
  tf[tf] = df[tf, title] == 'Insufficient Information'
  
  df[tf, title] = NA
  df[tf, code] = NA
  df[tf, prob] = NA
  
  return(df)
}
```

```{r read}
before_filename <- list.files(path = './data/',
                              pattern = '^coded_before_[0-9]{8}_[0-9]{8}.csv$',
                              full.names = T)

before = sort(before_filename, decreasing=T)[1]
before_df <- fread(before, data.table=FALSE) %>% 
  select(CASE_ID,
         NAICS_TITLE,
         NAICS_CODE,
         NAICS_PROB,
         SOC_TITLE,
         SOC_CODE,
         SOC_PROB)

after_filename <- list.files(path = './data/',
                             pattern = '^coded_io_[0-9]{8}_[0-9]{8}.csv$',
                             full.names = T)

after = sort(after_filename, decreasing=T)[1]
after_df <- fread(after, data.table=FALSE) %>% 
  select(CASE_ID,
         NAICS_TITLE,
         NAICS_CODE,
         NAICS_PROB,
         SOC_TITLE,
         SOC_CODE,
         SOC_PROB
  )
```

```{r transform}
comb_df <- before_df %>% 
  full_join(after_df, by="CASE_ID", suffix=c("_bef", "_aft")) %>% 
  insufficient_na("SOC_CODE_bef", "SOC_TITLE_bef", "SOC_PROB_bef") %>% 
  insufficient_na("NAICS_CODE_bef", "NAICS_TITLE_bef", "NAICS_PROB_bef") %>% 
  insufficient_na("SOC_CODE_aft", "SOC_TITLE_aft", "SOC_PROB_aft") %>% 
  insufficient_na("NAICS_CODE_aft", "NAICS_TITLE_aft", "NAICS_PROB_aft") %>%
  mutate(across(contains("_PROB_"), as.numeric)) %>% 
  mutate(across(contains("_PROB_"), function(x) if_else(is.na(x), 0, x)))

comb_df <- comb_df %>% mutate(NAICS_PROB_present_bef = NAICS_PROB_bef > 0,
                              SOC_PROB_present_bef = SOC_PROB_bef > 0,
                              NAICS_PROB_present_aft = NAICS_PROB_aft > 0,
                              SOC_PROB_present_aft = SOC_PROB_aft > 0)
```

```{r total}
### Get total # of rows in dataset
n = nrow(comb_df)
```

```{r completeness}
# Analyze completeness of dataset

# Before enhancements
comp_bef_i_count <- sum(comb_df$NAICS_PROB_present_bef)
comp_bef_i_prop <- comp_bef_i_count/n
comp_bef_o_count <- sum(comb_df$SOC_PROB_present_bef)
comp_bef_o_prop <- comp_bef_o_count/n

# After enhancements
comp_aft_i_count <- sum(comb_df$NAICS_PROB_present_aft)
comp_aft_i_prop <- comp_aft_i_count/n
comp_aft_o_count <- sum(comb_df$SOC_PROB_present_aft)
comp_aft_o_prop <- comp_aft_o_count/n

# Improvements
improve_i_count <- comp_aft_i_count - comp_bef_i_count 
improve_i_prop <- improve_i_count/n 
improve_o_count <- comp_aft_o_count - comp_bef_o_count 
improve_o_prop <- improve_o_count/n 

# Build summary df
data.frame('Initial Coding Rate' = c('Industry Codes'=glue("{format(comp_bef_i_count, big.mark = ',')} ({round(100*comp_bef_i_prop, digits=1)}%)"), 
                                     'Ocupation Codes'=glue("{format(comp_bef_o_count, big.mark = ',')} ({round(100*comp_bef_o_prop, digits=1)}%)")), 
           'After Enhancements' = c(glue("{format(comp_aft_i_count, big.mark = ',')} ({round(100*comp_aft_i_prop, digits=1)}%)"), 
                                    glue("{format(comp_aft_o_count, big.mark = ',')} ({round(100*comp_aft_o_prop, digits=1)}%)")),
           'Improvements' = c(glue("{format(improve_i_count, big.mark = ',')} ({round(100*improve_i_prop, digits=1)}%)"), 
                              glue("{format(improve_o_count, big.mark = ',')} ({round(100*improve_o_prop, digits=1)}%)")))
```

```{r accuracy}
# Analyze accuracy of added data

accuracy_i <- comb_df %>% filter(NAICS_PROB_present_aft & !NAICS_PROB_present_bef)
accuracy_o <- comb_df %>% filter(SOC_PROB_present_aft & !SOC_PROB_present_bef)
table(accuracy_i$NAICS_PROB_aft > 0.6)/nrow(accuracy_i)
table(accuracy_o$SOC_PROB_aft > 0.6)/nrow(accuracy_o)
```

```{r visuals}
# Industry hist
histogram <- ggplot(accuracy_i, aes(x = NAICS_PROB_aft)) +
  geom_histogram(breaks=seq(0,1,by=0.05), fill = "#DBE6EF", color = "#5084B3") +
  geom_vline(xintercept = 0.6, color = "black", linetype = "dashed") +
  labs(title = glue("Added Industry (n={nrow(accuracy_i)})"), x = "Probability", y = "Frequency", color='#5084B3') +
  scale_x_continuous(limits=c(0,1), breaks = seq(0,1,by=0.2), expand = c(0,0)) +
  scale_y_continuous(expand = c(0,0)) +
  theme_minimal() + 
  theme(text = element_text(colour = "#5084B3"),
        axis.line.x = element_line(color="#5084B3"),
        axis.line.y = element_line(color="#5084B3"),
        axis.text.x = element_text(color="#5084B3"),
        axis.text.y = element_text(color="#5084B3"))
  
# Print the histogram
print(histogram)

# Occ histogram
histogram <- ggplot(accuracy_o, aes(x = SOC_PROB_aft)) +
  geom_histogram(breaks=seq(0,1,by=0.05), fill = "#E0EAD9", color = "#92B579") +
  geom_vline(xintercept = 0.6, color = "black", linetype = "dashed") +
  labs(title = glue("Added Occupation (n={nrow(accuracy_o)})"), x = "Probability", y = "Frequency", color='#92B579') +
  scale_x_continuous(limits=c(0,1), breaks = seq(0,1,by=0.2), expand = c(0,0)) +
  scale_y_continuous(expand = c(0,0)) +
  theme_minimal() + 
  theme(text = element_text(colour = "#92B579"),
        axis.line.x = element_line(color="#92B579"),
        axis.line.y = element_line(color="#92B579"),
        axis.text.x = element_text(color="#92B579"),
        axis.text.y = element_text(color="#92B579"))

# Print the histogram
print(histogram)
```
